import {zones,zoneProfiles,missions,offerings,vendorRows,graph,roadmap,kpis,guardrails,sources,assumptions} from './data.js';

const nav=[
  ['overview','dashboard','National twin'],['missions','crisis_alert','Mission threads'],['offerings','deployed_code','Offer portfolio'],
  ['graph','hub','Knowledge graph'],['roadmap','conversion_path','Roadmap'],['governance','policy','Governance'],['sources','library_books','Sources']
];
const state={view:location.hash.slice(1)||'overview',selectedState:'Nigeria',selectedZone:'National',mapMode:'readiness',offerGroup:0,mission:null};
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const icon=n=>`<span class="material-symbols-rounded" aria-hidden="true">${n}</span>`;
const zoneFor=name=>Object.entries(zones).find(([,states])=>states.includes(name))?.[0];
const fmt=n=>String(n).padStart(2,'0');

function shell(){
  $('#app').innerHTML=`<div class="app-shell">
    <aside class="sidebar" id="sidebar" aria-label="Primary navigation">
      <div class="brand"><div class="brand-mark">TSL</div><div class="brand-text"><strong>National Resilience Twin</strong><small>Strategy foundation • v1</small></div></div>
      <div class="nav-label">Strategy workspace</div><nav class="nav-list">${nav.map(([id,ic,l])=>`<button class="nav-item" data-view="${id}" aria-label="${l}">${icon(ic)}<span>${l}</span></button>`).join('')}</nav>
      <div class="sidebar-note"><strong>${icon('verified_user')}Bounded prototype</strong>No live operations, personal data, target locations or autonomous enforcement.</div>
    </aside>
    <div class="content-shell">
      <header class="topbar"><button class="icon-button mobile-menu" id="menu" aria-label="Open navigation">${icon('menu')}</button><div class="page-title"><strong id="top-title">National twin</strong><span>Prepared by TSL Logistics • KONGSBERG + Exail opportunity architecture</span></div><div class="top-actions"><span class="status-chip"><i class="status-dot"></i>Illustrative strategic model</span><button class="icon-button" id="brief" aria-label="Open executive brief">${icon('description')}</button><button class="icon-button" id="theme" aria-label="Toggle colour theme">${icon('contrast')}</button></div></header>
      <main id="main" tabindex="-1">${views()}</main>
    </div>
  </div>
  <nav class="mobile-bottom" aria-label="Mobile navigation">${nav.slice(0,5).map(([id,ic,l])=>`<button data-view="${id}">${icon(ic)}<span>${l.replace(' threads','').replace(' portfolio','')}</span></button>`).join('')}</nav>
  <dialog class="dialog" id="brief-dialog"><div class="dialog-head"><div><strong>Executive brief</strong><div class="org">TSL Logistics proposal foundation</div></div><button class="icon-button" id="close-brief" aria-label="Close">${icon('close')}</button></div><div class="dialog-body"><textarea id="brief-text" readonly>${executiveBrief()}</textarea><div style="display:flex;gap:8px;margin-top:12px"><button class="action-button" id="copy-brief">${icon('content_copy')}Copy brief</button><button class="action-button secondary" onclick="window.print()">${icon('print')}Print / PDF</button></div></div></dialog>
  <div class="toast" role="status" aria-live="polite" id="toast"></div>`;
}

function views(){return `${overviewView()}${missionsView()}${offeringsView()}${graphView()}${roadmapView()}${governanceView()}${sourcesView()}`}
function head(eye,title,lede,extra=''){return `<div class="section-head"><div><div class="eyebrow">${eye}</div><h1>${title}</h1><p class="lede">${lede}</p></div>${extra||`<div class="disclosure">${icon('info')}Illustrative, national-level strategy. Validate every score and integration during formal discovery.</div>`}</div>`}

function overviewView(){return `<section class="view" id="view-overview" data-title="National twin">${head('TSL Logistics strategic intelligence','One national resilience picture. Multiple accountable owners.','A high-level digital twin joining security missions, critical services, hydrography, maritime awareness, infrastructure integrity and delivery readiness—without creating a centralised surveillance state.')}
  <div class="grid kpi-grid">
    ${metric('Mission portfolios','06','prioritised national threads',82)}${metric('Offer modules','30+','grouped for procurement',74)}${metric('Pilot horizon','90 days','to approved scope',58)}${metric('Design posture','Federated','sovereign by default',91)}
  </div>
  <div class="grid workspace">
    <article class="panel"><div class="panel-head"><div class="panel-title"><strong>Nigeria resilience twin</strong><span>37 state/FCT boundaries • aggregated zonal planning profiles</span></div><div class="segmented" aria-label="Map display"><button data-mapmode="readiness" class="active">Readiness</button><button data-mapmode="mission">Mission</button></div></div><div class="map-wrap"><div id="nigeria-map" role="img" aria-label="Interactive map of Nigeria states coloured by illustrative zonal readiness priority"></div><div class="map-legend"><span>Lower planning priority</span><i class="legend-swatch" style="background:#2b6357"></i><i class="legend-swatch" style="background:#b18b3a"></i><i class="legend-swatch" style="background:#a24f4f"></i><span>Higher</span></div></div></article>
    <aside class="panel inspector"><div class="panel-head"><div class="panel-title"><strong id="inspector-title">Nigeria</strong><span id="inspector-zone">National strategic baseline</span></div>${icon('travel_explore')}</div><div class="inspector-body" id="inspector-body"></div></aside>
  </div>
  <div class="grid activity-strip"><article class="panel activity"><div class="panel-title"><strong>Indicative delivery pulse</strong><span>Illustrative workstream load—not incident volume</span></div><div class="activity-bars">${[36,58,52,74,62,83,68,77,55,88,72,81].map(h=>`<i class="activity-bar" style="height:${h}%"></i>`).join('')}</div></article><article class="panel activity"><div class="panel-title"><strong>Architecture at a glance</strong><span>What the first national platform must connect</span></div><div class="legend-list"><div><strong>Sense</strong><span>authorised field, maritime, asset and public data</span></div><div><strong>Understand</strong><span>knowledge graph, models, provenance and confidence</span></div><div><strong>Coordinate</strong><span>referrals, resources, evidence and recovery</span></div></div></article></div>
</section>`}
function metric(label,value,sub,pct){return `<article class="metric"><div class="metric-top"><span>${label}</span>${icon('trending_up')}</div><div class="metric-value">${value}</div><small>${sub}</small><div class="progress"><span style="width:${pct}%"></span></div></article>`}

function missionsView(){return `<section class="view" id="view-missions" data-title="Mission threads">${head('Outcome architecture','Organise around public outcomes—not vendor catalogues.','Six mission threads connect Nigeria’s documented security priorities to clean, procurable service packages. Every thread starts with governance, existing assets and measurable outcomes.')}
  <div class="grid mission-grid">${missions.map(m=>`<button class="mission-card" data-mission="${m.id}" style="--accent:${m.color}"><span class="mission-icon">${icon(m.icon)}</span><h3>${m.title}</h3><p>${m.outcome}</p><div class="meta-row"><span class="tag">${m.horizon}</span><span class="tag">${m.vendors.join(' + ')}</span></div><span class="arrow">Inspect thread ${icon('arrow_forward')}</span></button>`).join('')}</div><div class="mission-detail" id="mission-detail"></div>
</section>`}

function offeringsView(){return `<section class="view" id="view-offerings" data-title="Offer portfolio">${head('Commercial structure','A modular offer stack TSL can lead, combine and sustain.','The portfolio separates infrastructure, advisory work, technology and managed services so government can procure outcomes in phases while retaining interoperability and exit rights.')}
  <div class="offering-tabs" role="tablist">${offerings.map((g,i)=>`<button class="tab-button ${i===0?'active':''}" data-offer="${i}" role="tab" aria-selected="${i===0}">${icon(g.icon)}${g.group}</button>`).join('')}</div><div class="grid offer-grid" id="offer-grid"></div>
  <div class="section-head" style="margin-top:34px"><div><div class="eyebrow">Partner fit</div><h2>One integrator, two complementary technology anchors</h2><p class="lede">TSL owns Nigerian delivery, asset operations and lifecycle accountability; KONGSBERG anchors integrated sensing and maritime systems; Exail adds high-end robotics, navigation and remote survey.</p></div></div>
  <div class="matrix-wrap"><table><thead><tr><th>Capability</th><th><span class="vendor-mark">KONGSBERG</span></th><th><span class="vendor-mark">Exail</span></th><th><span class="vendor-mark">TSL Logistics</span></th></tr></thead><tbody>${vendorRows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>
</section>`}

function graphView(){return `<section class="view" id="view-graph" data-title="Knowledge graph">${head('Sense-making layer','Relationships matter more than another wall of feeds.','The graph links mission owners, services, vendor capabilities and national outcomes with source provenance and permissions. In production it would hold claims—not uncontrolled copies of agency records.')}
  <div class="graph-shell"><div class="graph-panel"><svg id="knowledge-graph" viewBox="0 0 1000 600" role="img" aria-label="Interactive knowledge graph linking TSL, KONGSBERG, Exail, national services and agencies"></svg></div><aside class="graph-inspector" id="graph-inspector"><div class="eyebrow">Selected node</div><h2>TSL Logistics</h2><p class="lede">Prime integrator, Nigerian service operator and lifecycle-accountability layer.</p><div class="graph-key">${[['#68e0c3','Integrator'],['#7cb7ff','Platform'],['#b8a1ff','Technology partner'],['#ffd166','Mission'],['#ffad66','Public owner']].map(([c,l])=>`<div><i style="background:${c}"></i>${l}</div>`).join('')}</div><div class="assumption-box"><strong>Production rule</strong><p style="margin:5px 0 0;font-size:11px">Each edge carries source, legal basis, owner, confidence, time and access policy. Graph visibility never implies authorisation to act.</p></div></aside></div>
</section>`}

function roadmapView(){return `<section class="view" id="view-roadmap" data-title="Roadmap">${head('Execution path','Prove value in 90 days. Scale only what earns trust.','A phased path avoids an oversized national procurement, strengthens existing Nigerian programmes and makes local operating capability a contractual outcome—not a future promise.')}
  <div class="timeline">${roadmap.map(p=>`<article class="phase"><div class="phase-index">${p.phase}</div><div class="phase-time">${p.time}</div><div><h3>${p.title}</h3><p>${p.result}</p></div><ul>${p.actions.map(a=>`<li>${a}</li>`).join('')}</ul></article>`).join('')}</div>
</section>`}

function governanceView(){return `<section class="view" id="view-governance" data-title="Governance">${head('Trust architecture','National capability must be powerful—and visibly constrained.','The twin is designed for public safety, service continuity and accountable coordination. These controls must be specified, tested and funded alongside every technical component.')}
  <div class="grid gov-grid">${guardrails.map((g,i)=>`<article class="guardrail"><div class="guardrail-index">${fmt(i+1)}</div><div><h3>${g[0]}</h3><p>${g[1]}</p></div></article>`).join('')}</div>
  <div class="section-head" style="margin-top:36px"><div><div class="eyebrow">Benefits management</div><h2>Board-level measures</h2><p class="lede">Targets are proposed programme gates. Discovery establishes baselines and owners before they become contractual.</p></div></div><div class="matrix-wrap kpi-table"><table><thead><tr><th>Domain</th><th>Measure</th><th>Proposed gate</th></tr></thead><tbody>${kpis.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>
</section>`}

function sourcesView(){return `<section class="view" id="view-sources" data-title="Sources">${head('Evidence register','Documented capabilities. Explicit proposals. Visible assumptions.','This strategy separates what official sources support from what TSL is proposing. Links open the originating public source; dates and availability should be revalidated during procurement.',`<div class="source-tools"><button class="action-button secondary" id="export-sources">${icon('download')}Export register</button><input class="search" id="source-search" type="search" placeholder="Filter sources…" aria-label="Filter source register"></div>`)}
  <div class="source-list" id="source-list"></div><div class="assumption-box"><strong>Assumptions and boundaries</strong><ul>${assumptions.map(a=>`<li>${a}</li>`).join('')}</ul></div>
</section>`}

function executiveBrief(){return `TSL LOGISTICS — NIGERIA NATIONAL RESILIENCE TWIN\nHigh-level strategy foundation | KONGSBERG + Exail opportunity architecture\n\nPROPOSITION\nPosition TSL Logistics as Nigeria's sovereign delivery and lifecycle integrator for a federated homeland-security resilience platform. Build on existing national programmes and assets rather than replacing them. KONGSBERG contributes integrated maritime sensing, hydrography, autonomous underwater survey and situational-awareness capabilities. Exail contributes advanced supervised-autonomy, hydrographic robotics, inertial navigation, subsea positioning and remote survey.\n\nFIRST TWO LIGHTHOUSE PILOTS\n1. A bounded maritime/hydrographic data-fusion and survey productivity pilot, including NNS LANA technical readiness assessment and an uncrewed survey service demonstration.\n2. A critical-infrastructure integrity twin on a consenting TSL-managed asset, joining inspection, maintenance, cyber-physical risk, inventory and recovery data.\n\nWHY TSL\nTSL already documents expertise in petroleum terminals, pipeline management and surveillance, inventory technology, infrastructure development, HSSEQ, relationship management and supply-chain consultancy. Its differentiator is not reselling equipment; it is owning Nigerian integration, operations, maintenance, workforce transfer, service levels and benefits realisation.\n\nCOMMERCIAL MODEL\nBegin with paid discovery and two fixed-outcome pilots. Progress to modular managed services with uptime, data-quality, survey-throughput, asset-readiness, local-capacity and safeguards KPIs. Preserve open interfaces, Nigeria-controlled keys, source-system authority and exit rights.\n\nNON-NEGOTIABLES\nNo live or personal data in the prototype. No autonomous coercive decisions. No predictive policing. Named human decision owners, provenance and confidence on every material claim, purpose-based access, audit, retention, redress and independent oversight.\n\nDECISION REQUEST\nApprove a 90-day joint discovery involving TSL, mission-owning agencies and selected OEM teams to validate legal mandate, existing assets, baseline metrics, export-control constraints, architecture, pilot sites and commercial envelope.`}

function navigate(view){
  if(!nav.some(n=>n[0]===view))view='overview'; state.view=view; location.hash=view;
  $$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${view}`));
  $$('[data-view]').forEach(b=>{const active=b.dataset.view===view;b.classList.toggle('active',active);if(b.classList.contains('nav-item'))b.setAttribute('aria-current',active?'page':'false')});
  const label=nav.find(n=>n[0]===view)?.[2]||'National twin'; $('#top-title').textContent=label; $('#sidebar').classList.remove('open'); window.scrollTo({top:0,behavior:'smooth'});
  if(view==='overview')renderMap(); if(view==='graph')renderGraph();
}

function colorFor(zone,mode){
  if(mode==='mission'){return {'North West':'#965b58','North East':'#8d4e55','North Central':'#9a773d','South West':'#397463','South East':'#69668c','South South':'#2f7080'}[zone]||'#51645f'}
  const score=zoneProfiles[zone]?.score||55; return score>=80?'#914a50':score>=75?'#a2634d':score>=65?'#96763e':score>=60?'#666d53':'#2f6a5b';
}
function renderMap(){
  const root=$('#nigeria-map'); if(!root||root.dataset.ready)return; root.innerHTML='<div class="disclosure">Loading local boundary geometry…</div>';
  fetch('/nigeria-states.geojson').then(r=>r.json()).then(geo=>{
    const coords=[]; const walk=a=>{if(typeof a[0]==='number')coords.push(a);else a.forEach(walk)};geo.features.forEach(f=>walk(f.geometry.coordinates));
    const minX=Math.min(...coords.map(c=>c[0])),maxX=Math.max(...coords.map(c=>c[0])),minY=Math.min(...coords.map(c=>c[1])),maxY=Math.max(...coords.map(c=>c[1]));
    const W=760,H=610,pad=34;const project=([x,y])=>[pad+(x-minX)/(maxX-minX)*(W-pad*2),H-pad-(y-minY)/(maxY-minY)*(H-pad*2)];
    const pathGeom=g=>{const ring=r=>'M'+r.map(project).map(p=>p.join(',')).join('L')+'Z';return g.type==='Polygon'?g.coordinates.map(ring).join(' '):g.coordinates.flatMap(p=>p.map(ring)).join(' ')};
    root.innerHTML=`<svg viewBox="0 0 ${W} ${H}" width="100%" height="100%" aria-labelledby="map-title"><title id="map-title">Nigeria state boundaries by aggregated zonal planning profile</title>${geo.features.map(f=>{const n=f.properties.shapeName,z=zoneFor(n);return `<path class="state" tabindex="0" role="button" aria-label="${n}, ${z}" data-state="${n}" data-zone="${z}" d="${pathGeom(f.geometry)}" fill="${colorFor(z,state.mapMode)}"><title>${n} • ${z}</title></path>`}).join('')}</svg>`;root.dataset.ready='1';
    $$('.state').forEach(el=>{const select=()=>selectMapState(el.dataset.state,el.dataset.zone);el.addEventListener('click',select);el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select()}})});selectMapState('Nigeria','National');
  }).catch(()=>root.innerHTML='<div class="disclosure">Boundary file unavailable. The strategy remains accessible in the other views.</div>');
}
function selectMapState(name,zone){state.selectedState=name;state.selectedZone=zone;$$('.state').forEach(s=>s.classList.toggle('selected',s.dataset.state===name));const p=zone==='National'?{score:71,confidence:'Medium',posture:'Federated resilience',focus:['Protect people and territory','Secure prosperity and critical services','Strengthen accountable coordination'],summary:'A composite planning baseline across six public-outcome missions. It is not a current threat level or operational assessment.',priority:'Fund discovery, two lighthouse pilots, sovereign data governance and Nigerian lifecycle capacity before national scale.'}:zoneProfiles[zone];$('#inspector-title').textContent=name;$('#inspector-zone').textContent=zone==='National'?'National strategic baseline':zone;$('#inspector-body').innerHTML=`<div class="risk-score"><div><div class="label">Illustrative priority index</div><div class="score-number">${p.score}</div></div><span class="tag">Confidence: ${p.confidence}</span></div><div><div class="label">Planning posture</div><h3 style="margin-top:5px">${p.posture}</h3><p style="color:var(--md-sys-color-on-surface-variant);font-size:12px">${p.summary}</p></div><div><div class="label">Mission emphasis</div><ul class="focus-list">${p.focus.map(x=>`<li>${x}</li>`).join('')}</ul></div><div class="inspector-callout"><strong>TSL priority move</strong>${p.priority}</div><div class="disclosure">${icon('lock')}Aggregated planning content only. No live incidents, precise assets or tactical indicators.</div>`}
function updateMapColors(){state.mapMode=this.dataset.mapmode;$$('[data-mapmode]').forEach(b=>b.classList.toggle('active',b===this));$$('.state').forEach(s=>s.setAttribute('fill',colorFor(s.dataset.zone,state.mapMode)))}

function renderOffers(i=0){state.offerGroup=+i;const g=offerings[i];$('#offer-grid').innerHTML=g.items.map((x,j)=>`<article class="offer-item"><span class="num">${fmt(j+1)} / ${fmt(g.items.length)}</span><h3>${x[0]}</h3><p>${x[1]}</p></article>`).join('');$$('[data-offer]').forEach((b,j)=>{b.classList.toggle('active',j===+i);b.setAttribute('aria-selected',j===+i)})}
function renderMission(id){const m=missions.find(x=>x.id===id);state.mission=id;const d=$('#mission-detail');d.className='mission-detail open';d.innerHTML=`<div><div class="eyebrow">${m.lead}</div><h2>${m.title}</h2><div class="label">Problem to solve</div><p class="lede">${m.problem}</p><div class="label">Target outcome</div><p class="lede">${m.outcome}</p></div><div><div class="label">Proposed offer modules</div><div class="solution-grid">${m.offers.map(x=>`<div class="solution-item"><strong>${x}</strong></div>`).join('')}</div><div class="meta-row" style="margin-top:14px">${m.vendors.map(v=>`<span class="tag">${v}</span>`).join('')}<span class="tag">${m.horizon}</span></div></div>`;d.scrollIntoView({behavior:'smooth',block:'nearest'})}

const nodeInfo={
  'TSL Logistics':['Prime integrator','Own Nigerian service design, systems integration, HSSEQ, field logistics, lifecycle support, local capacity and benefits reporting.'],
  'National Resilience Twin':['Federated decision platform','A knowledge-and-workflow layer over authorised source systems; it exposes provenance, confidence and accountable ownership.'],
  'KONGSBERG':['Technology anchor','Documented strengths in maritime surveillance, cView/Foresight, AIS, hydrography, HUGIN, sonar, inspection and lifecycle support.'],
  'Exail':['Advanced technology anchor','Documented strengths in DriX supervised autonomy, hydrography, inertial navigation, subsea positioning, sonar and remote survey.']
};
function renderGraph(){const svg=$('#knowledge-graph');if(!svg||svg.dataset.ready)return;const colors={integrator:'#68e0c3',platform:'#7cb7ff',vendor:'#b8a1ff',mission:'#ffd166',agency:'#ffad66'};svg.innerHTML=`<g>${graph.edges.map(e=>{const a=graph.nodes[e[0]],b=graph.nodes[e[1]],mx=(a[2]+b[2])/2,my=(a[3]+b[3])/2;return `<line class="edge" x1="${a[2]}" y1="${a[3]}" x2="${b[2]}" y2="${b[3]}"></line><text class="edge-label" x="${mx}" y="${my}">${e[2]}</text>`}).join('')}</g><g>${graph.nodes.map((n,i)=>`<g class="node" tabindex="0" role="button" aria-label="${n[0]}" data-node="${i}" transform="translate(${n[2]},${n[3]})"><circle r="${n[1]==='integrator'?31:25}" fill="${colors[n[1]]}"></circle><text y="${n[1]==='integrator'?48:43}">${n[0]}</text></g>`).join('')}</g>`;svg.dataset.ready='1';$$('.node').forEach(n=>{const go=()=>selectNode(+n.dataset.node);n.addEventListener('click',go);n.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();go()}})})}
function selectNode(i){$$('.node').forEach(n=>n.classList.toggle('active',+n.dataset.node===i));const n=graph.nodes[i],info=nodeInfo[n[0]]||[n[1]==='mission'?'Mission outcome':'Public mission owner',n[1]==='mission'?'A bounded public-service thread connected through governed data, workflow and measurable readiness.':'Retains statutory authority, decision rights and source-data accountability.'];$('#graph-inspector').innerHTML=`<div class="eyebrow">${info[0]}</div><h2>${n[0]}</h2><p class="lede">${info[1]}</p><div class="assumption-box"><strong>Connected relationships</strong><ul>${graph.edges.filter(e=>e[0]===i||e[1]===i).map(e=>{const other=e[0]===i?graph.nodes[e[1]][0]:graph.nodes[e[0]][0];return `<li>${e[2]} → ${other}</li>`}).join('')}</ul></div>`}

function renderSources(q=''){const low=q.toLowerCase();const filtered=sources.filter(s=>Object.values(s).join(' ').toLowerCase().includes(low));$('#source-list').innerHTML=filtered.map(s=>`<a class="source-card" href="${s.url}" target="_blank" rel="noopener"><span class="tag">${s.tag}</span><div><strong>${s.title}</strong><span class="org">${s.org}</span></div><p>${s.note}</p><span class="open-icon">${icon('open_in_new')}</span></a>`).join('')||'<div class="disclosure">No source matches that filter.</div>'}
function exportSources(){const rows=[['Tag','Title','Organisation','URL','Relevance'],...sources.map(s=>[s.tag,s.title,s.org,s.url,s.note])];const csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='TSL-security-strategy-source-register.csv';a.click();URL.revokeObjectURL(a.href);toast('Source register exported')}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function theme(){const next=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=next;localStorage.setItem('tsl-theme',next);toast(`${next[0].toUpperCase()+next.slice(1)} theme`)}
function events(){
  document.addEventListener('click',e=>{const v=e.target.closest('[data-view]');if(v)navigate(v.dataset.view);const o=e.target.closest('[data-offer]');if(o)renderOffers(o.dataset.offer);const m=e.target.closest('[data-mission]');if(m)renderMission(m.dataset.mission);const mm=e.target.closest('[data-mapmode]');if(mm)updateMapColors.call(mm)});
  $('#menu').addEventListener('click',()=>$('#sidebar').classList.toggle('open'));$('#theme').addEventListener('click',theme);$('#brief').addEventListener('click',()=>$('#brief-dialog').showModal());$('#close-brief').addEventListener('click',()=>$('#brief-dialog').close());
  $('#copy-brief').addEventListener('click',()=>navigator.clipboard.writeText($('#brief-text').value).then(()=>toast('Executive brief copied')));
  $('#source-search').addEventListener('input',e=>renderSources(e.target.value));$('#export-sources').addEventListener('click',exportSources);window.addEventListener('hashchange',()=>navigate(location.hash.slice(1)||'overview'));
}

shell();events();renderOffers();renderSources();navigate(state.view);
